# Generated by Django 3.2 on 2021-05-26 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(help_text='Escriba su nombre', max_length=15, verbose_name='Nombre')),
                ('Email', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=30)),
                ('titulo', models.CharField(max_length=20)),
                ('fecha', models.DateField()),
            ],
        ),
    ]
